FROM node:alpine
WORKDIR /usr/mediators/

COPY package.json .
RUN npm install yarn -g --force
COPY . .

# RUN yarn install --production=false

EXPOSE 3000
# CMD ["node", "./build/index.js"]
CMD ["yarn", "dev"]